### ISSUE TITLE
Doesn't work on Raspberry Pi 3B+ on archlinux arm64

### ISSUE THREAD

**Issue by jshaker000** [TheNextLVL/RPi.GPIO.64#1]
I successfully installed the 64 bit version of archlinuxarm on my raspi.  
 I installed this library using git clone and sudo python setup.py  
This seemed to work correctly.
 I then tried to write a python script using the library (using the same functions from 32 bit, as  I believe they are the same), and was given the issue:
"Runtime error: this module can only be run on a raspberry pi!"

Let me know if I can provide any more details or help in debugging!

**Comment by TheNextLVL** [comment]
Hi @jshaker000 , first let's check that the revision it's correct, in a terminal do:
 ``` shell
$ hd /proc/device-tree/system/linux,revision
```
If you have a RPi 3b+ this should be your output:
```
00000000  00 a0 20 d3                                       |.. .|
0000000x
```
Second, let's see if the library it's detecting your RPI model. Run a python shell and execute:
``` python
>>> import RPi.GPIO as GPIO
>>> GPIO.RPI_INFO
```
This is my output:
``` shell
{'P1_REVISION': 3, 'RAM': '1024M', 'REVISION': 'a02082', 'TYPE': 'Pi 3', 'PROCESSOR': 'BCM2837', 'MANUFACTURER': 'Sony'}
```

If the program is detecting your revision, try to execute the python program with sudo or root user.

**Comment by jshaker000** [comment]
Hi, sorry for the delay. 
I am working on ARCHLINUX ARM 64
https://archlinuxarm.org/

When I went to run the first command, I found that 
`/proc/device-tree/system`
does not exist. this might be the source of the problem

When I ran 
`$ls /proc/device-tree/`

I got ...

`'address-cells' __symbols__ arm-pmu clocks cpus interrupt-parent memory name serial-number thermal-zones wifi-pwrseq 'size-cells' aliases chosen compatible framebuffer@3e7fe000 leds model phy soc timer`

I also ran 
`$uname -a`

and got

`Linux alarm 4.20.0-2-ARCH #1 SMP Fri Dec 28 19:33:32 MST 2018 aarch64 GNU/Linux`


Finally, when I ran the python code

I could not even import RPi.GPIO because of runtime error, this can only be run on a raspberry pi!

I hope this helps and let me know if I can provide you with anything else 

EDIT:
Corrected the name of the directory I ls'd into

**Comment by TheNextLVL** [comment]
Ok, this is the problem. Currently to detect the raspberry model is used the `/proc/device-tree/system/linux,revision` file that is generated by the kernel. It seems that the aarch linux kernel does not generate these files, so model detection fails.

All the tests I have done have been using the [official kernel](https://github.com/raspberrypi/linux).  

If you can pass me the contents of the files (from  `/proc/device-tree/system`) : `cpus`, `name`, `serial-number`, `model`. I will try to add support for model detection using Arch.  The objective is find the serial number in one of these files, for RPi3b+ is `a020d3`.

First try to read with `cat`, if is a binary file (usualy you don't see any with `cat`) try with `hd`

**Comment by jshaker000** [comment]
Hi, I looked around in those files and here are my results (I used xxd rather than hd for hexdumping)

Also I edited my above comment, the deepest I could follow you was

/proc/device-tree

I did not even have a system folder

My results are:

`$xxd /proc/device-tree/name`
00000000:       00                                      | .

`$xxd /proc/device-tree/serial-number`
00000000:       3030 3030 3030 3030 6533 6134 3964 6262 | 00000000e3a49dbb
00000010:       00                                      | .

`$xxd /proc/device-tree/model`
00000000:       5261 7370 6265 7272 7920 5069 2033 204d | Raspberry Pi 3 M
00000010:       6f64 656c 2042 2b00                     | odel B+.

/proc/device-tree/cpus was a directory, not a file

`$ls /proc/device-tree/cpus`
`'#address-calls' '#size-cells' cpu@0 cpu@1 cpu@2 cpu@3 enable-method name phandle`

`$xxd /proc/deivce-tree/cpus/name`
00000000:       6370 7573 00

Let me know if this helps or if you have any other idea to work off of

**Comment by TheNextLVL** [comment]
Hi @jshaker000 , sorry for the delay. I added a "quick fix" to check if works to the repository. To test just clone or download the repo as .zip and istall as usual.

**Comment by jshaker000** [comment]
Hi, I git pulled the new code and re ran setup.py  
I am still getting the same error that I got when I first made this post ...

**Comment by TheNextLVL** [comment]
Try now, If don't work tell me if the /proc/device-tree/model is a file or a binary

**Comment by jshaker000** [comment]
Hi, I have a different error now! (I git pulled and re ran setup.py)
The module now accepts that I do have a raspberry pi, but I get the following error

`>>>>import RPI.GPIO as GPIO`
`Traceback (most recent call last):`
     `file "<stdin>", line 1, in <module>`
    `file "/root/rpi_gpio64/RPi/GPIO/__init__.py", line 23, in <module>
from RPi._GPIO import *`
`ModuleNotFoundError: No module named RPi._GPIO`

**Comment by TheNextLVL** [comment]
@jshaker000 jajaja, I made the same mistake some time ago. This error is because you are in the folder of the package and there is a folder named `RPi`, thus when you do import RPi.GPIO the python shell search in the local folder the package and fails.
Go to another folder not inside you `rpi_gpio64` folder and try again.

**Comment by jshaker000** [comment]
Thanks! It works now!
